trigger:
  branches:
    include:
      - main

pr:
  - main

resources:
  repositories:
    - repository: azd
      type: github
      name: amolanol5/azd
      endpoint: amolanol5

parameters:
  - name: environment
    displayName: Environment
    type: string
    default: None
    values:
      - DEV


extends:
  template: test.yaml@azd
  parameters:
    test: $(test)
  deployConfig:
    - ${{ if eq(parameters.environment, 'Dev') }}:
        - stage: DEV  

