trigger:
  branches:
    include:
      - main

pr:
  - main

resources:
  repositories:
    - repository: azd
      type: github
      name: amolanol5/azd
      endpoint: amolanol5

parameters:
  - name: environment
    displayName: Environment
    type: string
    default: None
    values:
      - Dev
      - UAT

extends:
  template: test.yaml@azd
  parameters:
    folder_cognito_users: cognito-delete-users
    deployConfig:
      - ${{ if eq(parameters.environment, 'Dev') }}:
          - stage: DEV 

      - ${{ if eq(parameters.environment, 'UAT') }}:
          - stage: UAT 