trigger:
  branches:
    include:
      - main

pr:
  - main

resources:
  repositories:
    - repository: azd
      type: github
      name: amolanol5/azd
      endpoint: amolanol5

extends:
  template: test.yaml@azd
  parameters:
    test: $(test)
